version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack-pro:latest
    healthcheck:
      test: ["CMD", "awslocal", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - localstack-net
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  localstack-net:
    driver: bridge
