version = 0.1
[local]
[local.deploy]
[local.deploy.parameters]
stack_name = "aws-leaderboard-app-local"
s3_bucket = "sam-cli-managed-default"
s3_prefix = "aws-leaderboard-app-local"
region = "us-east-1"
confirm_changeset = false           # Set to false for automated local deployments
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
disable_rollback = true
parameter_overrides = "ProjectName=\"aws-leaderboard-app-local\" LeaderboardTableName=\"leaderboard-local\" AllowedOrigin=\"http://localhost:5173\""
debug = false
guided = false

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "aws-leaderboard-app-prod"
s3_bucket = "aws-sam-cli-source-bucket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = false
s3_prefix = "aws-leaderboard-app-prod"
parameter_overrides = ""
image_repositories = []
debug = false
guided = true
